## Banking Loans Data Analysis Overview and Loading

### Project Overview

This project focuses on analyzing a banking loans dataset to assess data quality, perform data cleaning, explore
patterns, and answer relevant business questions using Python and its data analysis libraries.

The project follows the data analysis workflow:
Data Understanding, Data Exploration, Data Cleaning, Feature Engineering (if required), and Data Analysis.

### Dataset Understanding

The Banking Loans Dataset contains information about loan accounts, customer characteristics, loan terms, credit risk indicators, and repayment-related metrics.

The dataset is used to assess data quality, perform data cleaning, explore patterns, and answer business-related questions using data analysis and visualization.

### Dataset:

| Column                    | Description                                                      |
| ------------------------- | ---------------------------------------------------------------- |
| `record_id`               | Unique identifier for each record in the dataset                 |
| `loan_id`                 | Identifier of the loan account                                   |
| `customer_age`            | Age of the customer in years                                     |
| `city`                    | City where the customer or loan account is located               |
| `branch`                  | Bank branch associated with the loan account                     |
| `employment_status`       | Employment status of the customer                                |
| `annual_income_egp`       | Customer's annual income in Egyptian Pounds (EGP)                |
| `loan_type`               | Type of loan associated with the account                         |
| `loan_purpose`            | Purpose for which the loan was taken                             |
| `loan_amount_egp`         | Original loan amount in Egyptian Pounds (EGP)                    |
| `interest_rate_pct`       | Interest rate applied to the loan, expressed as a percentage     |
| `term_months`             | Loan repayment term in months                                    |
| `credit_score`            | Customer's credit score used as an indicator of creditworthiness |
| `debt_to_income_pct`      | Customer's debt-to-income ratio, expressed as a percentage       |
| `risk_grade`              | Risk classification assigned to the loan or customer             |
| `origination_date`        | Date on which the loan was originated                            |
| `application_channel`     | Channel through which the loan application was submitted         |
| `loan_status`             | Current status of the loan account                               |
| `monthly_installment_egp` | Monthly loan installment amount in Egyptian Pounds (EGP)         |
| `remaining_balance_egp`   | Outstanding loan balance remaining in Egyptian Pounds (EGP)      |

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

### Load the Dataset

The Banking Loans Dataset will be loaded into a Pandas DataFrame to prepare it for data inspection, cleaning, analysis, and visualization.

In [2]:
df = pd.read_csv('banking_loans_mid_project_FINAL.csv')
df.head()

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
0,1,LN109160,32.0,Aswan,Mansoura Branch,Salaried,34141.0,Mortgage,Education,1155415,10.64,36,555.0,95.00,E,1/19/2025,Relationship Manager,Defaulted,37630.14,431740.31
1,2,LN101801,66.0,Aswan,Aswan Branch,Salaried,34631.0,Education Loan,Medical,22238,7.22,36,514.0,57.15,E,10/20/2023,Branch,Active,688.87,17359.26
2,3,LN102666,29.0,Port Said,Mansoura Branch,Self-Employed,49700.0,Education Loan,Medical,236672,11.75,120,725.0,25.27,B,11/26/2019,Online,Active,3361.43,113965.42
3,4,LN102617,43.0,Giza,Giza Main,Salaried,14385.0,Business Loan,Education,183922,16.34,60,629.0,82.46,D,7/12/2021,Branch,Active,4505.91,108513.48
4,5,LN110048,61.0,Ismailia,Cairo Main,Business Owner,19550.0,Mortgage,Medical,182772,6.58,72,756.0,55.46,A,8/25/2023,Mobile App,Closed,3079.35,0.00

In [3]:
df.shape

(12035, 20)

## Quality Assessment and Statistical Summary (Categorical/Numerical)

### 1. Checking Duplicates & Missing Values

In [4]:
df.dtypes

record_id                    int64
loan_id                     object
customer_age               float64
city                        object
branch                      object
employment_status           object
annual_income_egp          float64
loan_type                   object
loan_purpose                object
loan_amount_egp              int64
interest_rate_pct          float64
term_months                  int64
credit_score               float64
debt_to_income_pct         float64
risk_grade                  object
origination_date            object
application_channel         object
loan_status                 object
monthly_installment_egp    float64
remaining_balance_egp      float64
dtype: object

In [5]:
df.isnull().sum()

record_id                    0
loan_id                      0
customer_age                 6
city                       100
branch                       0
employment_status          100
annual_income_egp          100
loan_type                    0
loan_purpose               100
loan_amount_egp              0
interest_rate_pct          100
term_months                  0
credit_score               100
debt_to_income_pct           0
risk_grade                   0
origination_date             0
application_channel          0
loan_status                  0
monthly_installment_egp      0
remaining_balance_egp        0
dtype: int64

In [6]:
df.isna().mean().round(4) * 100

record_id                  0.00
loan_id                    0.00
customer_age               0.05
city                       0.83
branch                     0.00
employment_status          0.83
annual_income_egp          0.83
loan_type                  0.00
loan_purpose               0.83
loan_amount_egp            0.00
interest_rate_pct          0.83
term_months                0.00
credit_score               0.83
debt_to_income_pct         0.00
risk_grade                 0.00
origination_date           0.00
application_channel        0.00
loan_status                0.00
monthly_installment_egp    0.00
remaining_balance_egp      0.00
dtype: float64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

,record_id,customer_age,annual_income_egp,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,monthly_installment_egp,remaining_balance_egp
count,12035.000000,12029.000000,11935.000000,1.203500e+04,11935.000000,12035.000000,11935.000000,12035.000000,12035.000000,1.203500e+04
mean,6018.000000,43.986200,42460.329032,3.709273e+05,13.021895,81.387619,675.697277,54.353267,10255.659091,1.752317e+05
std,3474.349579,13.471384,25135.185995,4.951326e+05,3.732852,61.460207,73.961150,24.546015,18251.612672,2.956804e+05
min,1.000000,18.000000,4199.000000,5.000000e+03,0.000000,12.000000,363.000000,5.520000,70.630000,0.000000e+00
25%,3009.500000,32.000000,25238.500000,8.378200e+04,9.830000,36.000000,625.000000,34.470000,1878.890000,1.917110e+04
50%,6018.000000,44.000000,36566.000000,1.884660e+05,13.060000,60.000000,677.000000,54.310000,4464.520000,6.868319e+04
75%,9026.500000,56.000000,52919.500000,4.542800e+05,16.230000,120.000000,726.000000,73.105000,11295.535000,2.000946e+05
max,12035.000000,67.000000,250000.000000,5.000000e+06,19.500000,240.000000,850.000000,95.000000,446867.930000,4.024504e+06

In [9]:
df.nunique()

record_id                  12035
loan_id                    11965
customer_age                  48
city                          22
branch                         6
employment_status              5
annual_income_egp          10793
loan_type                      6
loan_purpose                   7
loan_amount_egp            11848
interest_rate_pct           1302
term_months                   10
credit_score                 401
debt_to_income_pct          6013
risk_grade                     5
origination_date            2532
application_channel            4
loan_status                   14
monthly_installment_egp    11913
remaining_balance_egp       9992
dtype: int64

In [10]:
df["loan_id"].duplicated().sum()

np.int64(70)

In [11]:
df.loc[df["loan_id"].duplicated(keep=False), "loan_id"].value_counts()

loan_id
LN104160    2
LN111813    2
LN107200    2
LN106048    2
LN110932    2
           ..
LN108619    2
LN100472    2
LN105059    2
LN100012    2
LN109130    2
Name: count, Length: 70, dtype: int64

In [12]:
duplicate_loans = df[df["loan_id"].duplicated(keep=False)].sort_values("loan_id")
duplicate_loans

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
10394,10395,LN100012,56.0,Alexandria,Aswan Branch,Retired,13275.0,Education Loan,Education,77496,7.95,60,734.0,31.54,B,9/5/2021,Branch,Closed,1569.49,0.00
10429,10430,LN100012,56.0,Alexandria,Aswan Branch,Retired,13275.0,Education Loan,Education,77496,7.95,60,734.0,31.54,B,9/5/2021,Branch,Closed,1569.49,0.00
11090,11091,LN100191,62.0,Aswan,Cairo Main,Unemployed,43729.0,Personal Loan,Business Expansion,80499,7.26,240,624.0,57.31,D,3/16/2025,Mobile App,Restructured,636.74,34658.92
7162,7163,LN100191,62.0,Aswan,Cairo Main,Unemployed,43729.0,Personal Loan,Business Expansion,80499,7.26,240,624.0,57.31,D,3/16/2025,Mobile App,Restructured,636.74,34658.92
6564,6565,LN100247,53.0,Aswan,Giza Main,Self-Employed,30954.0,Business Loan,Education,222822,16.26,36,723.0,48.24,B,5/19/2025,Online,Closed,7862.38,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6871,6872,LN111237,38.0,Giza,Alexandria Main,Salaried,15544.0,Auto Loan,Home Purchase,112095,12.61,72,796.0,76.27,A,3/16/2024,Mobile App,Defaulted,2227.19,60484.51
9916,9917,LN111279,46.0,Cairo,Tanta Branch,Salaried,48514.0,Home Improvement,Medical,369667,14.09,180,675.0,38.02,C,8/15/2020,Branch,Closed,4945.38,0.00
9185,9186,LN111279,46.0,Cairo,Tanta Branch,Salaried,48514.0,Home Improvement,Medical,369667,14.09,180,675.0,38.02,C,8/15/2020,Branch,Closed,4945.38,0.00
81,82,LN111813,43.0,Cairo,Aswan Branch,Salaried,32577.0,Home Improvement,Personal Expenses,282666,19.27,60,638.0,63.68,D,3/18/2024,Relationship Manager,Defaulted,7374.58,170429.63
4186,4187,LN111813,43.0,Cairo,Aswan Branch,Salaried,32577.0,Home Improvement,Personal Expenses,282666,19.27,60,638.0,63.68,D,3/18/2024,Relationship Manager,Defaulted,7374.58,170429.63

In [13]:
duplicate_loans.drop(columns=["record_id", "loan_id"]).duplicated().sum()

np.int64(64)

In [14]:
duplicate_loans.groupby("loan_id").nunique().loc[lambda x: x.max(axis=1) > 1]

,record_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
loan_id,,,,,,,,,,,,,,,,,,,
LN100012,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100191,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100247,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100472,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN100694,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LN111139,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111148,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111237,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111279,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN111813,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [15]:
duplicate_comparison = duplicate_loans.drop(columns=["record_id"]).groupby("loan_id").nunique()

duplicate_comparison[duplicate_comparison.max(axis=1) > 1]

Empty DataFrame
Columns: [customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

### 2. Checking Categorical & Miss-Matching Values

In [16]:
df["loan_status"].value_counts()

loan_status
Active           5986
Defaulted        2244
Closed           1983
Restructured     1184
Written Off       613
active              7
 Active             4
 Defaulted          4
restructured        3
 Written Off        2
closed              2
written off         1
defaulted           1
 Restructured       1
Name: count, dtype: int64

In [17]:
df["loan_status"].unique()

array(['Defaulted', 'Active', 'Closed', 'Written Off', 'Restructured',
       'written off', 'active', 'defaulted', ' Defaulted', 'restructured',
       ' Active', 'closed', ' Restructured', ' Written Off'], dtype=object)

In [18]:
df["employment_status"].value_counts()

employment_status
Salaried          6312
Self-Employed     2261
Business Owner    1454
Retired           1191
Unemployed         717
Name: count, dtype: int64

In [19]:
df["city"].value_counts()

city
Mansoura       1690
Giza           1483
Cairo          1482
Aswan          1470
Alexandria     1468
Ismailia       1441
Tanta          1440
Port Said      1435
aswan             4
alexandria        3
 Ismailia         3
mansoura          2
port said         2
 Alexandria       2
 Tanta            2
tanta             2
ismailia          1
 Aswan            1
 Cairo            1
giza              1
cairo             1
 Mansoura         1
Name: count, dtype: int64

In [20]:
df["branch"].value_counts()

branch
Aswan Branch       2075
Giza Main          2074
Tanta Branch       2022
Mansoura Branch    1976
Alexandria Main    1961
Cairo Main         1927
Name: count, dtype: int64

In [21]:
df["loan_type"].value_counts()

loan_type
Personal Loan       3035
Business Loan       2561
Mortgage            2137
Auto Loan           1853
Home Improvement    1284
Education Loan      1165
Name: count, dtype: int64

In [22]:
df["loan_purpose"].value_counts()

loan_purpose
Medical               1895
Personal Expenses     1708
Education             1697
Business Expansion    1691
Home Purchase         1676
Vehicle Purchase      1654
Debt Consolidation    1614
Name: count, dtype: int64

In [23]:
df["risk_grade"].value_counts()

risk_grade
C    3108
B    2587
D    2517
A    1965
E    1858
Name: count, dtype: int64

In [24]:
df["application_channel"].value_counts()

application_channel
Branch                  4705
Online                  2975
Mobile App              2515
Relationship Manager    1840
Name: count, dtype: int64

In [25]:
df["origination_date"].unique()[:20]   ## month day or day month

array(['1/19/2025', '10/20/2023', '11/26/2019', '7/12/2021', '8/25/2023',
       '4/5/2024', '7/30/2024', '9/27/2025', '1/22/2025', '10/9/2023',
       '12/10/2019', '1/22/2019', '4/3/2023', '6/29/2024', '8/23/2022',
       '4/16/2023', '1/12/2022', '7/13/2024', '12/9/2024', '1/9/2024'],
      dtype=object)

In [26]:
pd.to_datetime(df["origination_date"], errors="coerce").isna().sum()

np.int64(0)

### 3. Checking Numerical Variables

In [27]:
df["interest_rate_pct"].value_counts().sort_index().head(15)

interest_rate_pct
0.00     1
6.50     4
6.51    16
6.52    11
6.53    10
6.54    12
6.55    10
6.56     6
6.57     9
6.58     6
6.59     8
6.60    12
6.61     8
6.62     7
6.63    11
Name: count, dtype: int64

In [28]:
df[df["interest_rate_pct"] == 0]

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
2677,2678,LN111911,22.0,Port Said,Mansoura Branch,Salaried,13833.0,Mortgage,Medical,369282,0.0,72,636.0,95.0,D,6/12/2023,Mobile App,Restructured,7281.13,309358.76

In [29]:
df[(df["credit_score"] < 300) | (df["credit_score"] > 850)]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [30]:
df[(df["customer_age"] < 18) | (df["customer_age"] > 100)]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [31]:
df[(df["debt_to_income_pct"] < 0) | (df["debt_to_income_pct"] > 100)]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [32]:
df[df["annual_income_egp"] <= 0]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [33]:
df[df["loan_amount_egp"] <= 0]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [34]:
df[df["monthly_installment_egp"] <= 0]

Empty DataFrame
Columns: [record_id, loan_id, customer_age, city, branch, employment_status, annual_income_egp, loan_type, loan_purpose, loan_amount_egp, interest_rate_pct, term_months, credit_score, debt_to_income_pct, risk_grade, origination_date, application_channel, loan_status, monthly_installment_egp, remaining_balance_egp]
Index: []

In [35]:
df.groupby("loan_status")["remaining_balance_egp"].agg(["count", "min", "max", "mean"]).round(2)

               count        min         max       mean
loan_status
 Active            4   22456.55   379113.46  175148.56
 Defaulted         4   18514.49   286887.22  126973.66
 Restructured      1  520767.93   520767.93  520767.93
 Written Off       2    9446.70    29978.25   19712.47
Active          5986    1244.74  4024504.19  179446.01
Closed          1983       0.00        0.00       0.00
Defaulted       2244    1396.36  4012521.11  256818.31
Restructured    1184    2416.09  2769925.28  256079.46
Written Off      613    1866.21  3271091.40  248418.02
active             7   16486.82   381642.74  102026.18
closed             2       0.00        0.00       0.00
defaulted          1  334007.95   334007.95  334007.95
restructured       3    5240.18    26659.37   16850.86
written off        1  103600.24   103600.24  103600.24

### Conclusion: Initial Data Quality Assessment

####

The dataset was reviewed for missing values, duplicate records, duplicate loan IDs, categorical inconsistencies, data types, and basic numerical validity.

The main data quality issues identified were:

- Missing values in 7 columns.
- Duplicate `loan_id` values.
- Inconsistent formatting in the `city` column.
- Inconsistent formatting in the `loan_status` column.
- `origination_date` stored as an object instead of datetime.
- One potential anomaly in `interest_rate_pct` with a value of 0.00%.

No full-row duplicates were found, and no invalid ranges were identified for the main numerical fields checked.

The identified issues will be addressed during the data cleaning stage.

## Data Cleaning

### Solving `city` inconsistent formatting and missing values Issues

In [36]:
df["city"] = df["city"].str.strip().str.title()
df["city"]

0            Aswan
1            Aswan
2        Port Said
3             Giza
4         Ismailia
           ...
12030    Port Said
12031        Cairo
12032    Port Said
12033     Mansoura
12034         Giza
Name: city, Length: 12035, dtype: object

In [37]:
df["city"].value_counts(dropna=False)

city
Mansoura      1693
Cairo         1484
Giza          1484
Aswan         1475
Alexandria    1473
Ismailia      1445
Tanta         1444
Port Said     1437
NaN            100
Name: count, dtype: int64

In [38]:
df[df["city"].isna()]

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
26,27,LN100725,31.0,NaN,Cairo Main,Retired,116646.0,Personal Loan,Medical,364820,7.24,240,668.0,8.36,C,4/10/2019,Online,Active,2881.24,300203.29
349,350,LN105359,63.0,NaN,Cairo Main,Salaried,16681.0,Personal Loan,Education,56370,NaN,72,681.0,49.46,C,8/19/2021,Online,Active,1021.14,31046.52
724,725,LN108620,41.0,NaN,Giza Main,Salaried,37038.0,Personal Loan,Medical,46135,11.26,180,662.0,64.14,C,2/8/2019,Branch,Active,531.93,41973.34
809,810,LN101057,35.0,NaN,Alexandria Main,Salaried,52498.0,Home Improvement,Vehicle Purchase,226265,10.02,84,824.0,39.01,A,6/7/2021,Branch,Active,3758.60,192884.84
893,894,LN110974,25.0,NaN,Cairo Main,Salaried,199423.0,Business Loan,Medical,1411568,11.84,24,696.0,58.72,C,3/7/2023,Relationship Manager,Active,66341.99,641899.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11458,11459,LN109093,60.0,NaN,Alexandria Main,Business Owner,20279.0,Business Loan,Medical,280117,7.79,48,604.0,81.58,D,1/16/2021,Online,Written Off,6810.90,118574.16
11580,11581,LN111969,44.0,NaN,Aswan Branch,Unemployed,61019.0,Business Loan,Debt Consolidation,172687,14.54,84,766.0,57.26,A,9/30/2021,Online,Defaulted,3287.89,145393.30
11656,11657,LN106101,49.0,NaN,Mansoura Branch,Salaried,34687.0,Home Improvement,Medical,81250,16.57,72,606.0,63.10,D,1/14/2021,Branch,Defaulted,1788.05,59125.31
11754,11755,LN111632,49.0,NaN,Tanta Branch,Retired,30251.0,Business Loan,Business Expansion,392273,7.80,180,520.0,12.67,E,12/29/2024,Online,Active,3703.62,210485.92
11864,11865,LN101990,65.0,NaN,Mansoura Branch,Self-Employed,22311.0,Personal Loan,Personal Expenses,14484,13.16,60,750.0,38.49,A,5/5/2025,Branch,Closed,330.75,0.00

In [39]:
pd.crosstab(df['city'], df['branch'])

branch,Alexandria Main,Aswan Branch,Cairo Main,Giza Main,Mansoura Branch,Tanta Branch
city,,,,,,
Alexandria,251,248,243,262,227,242
Aswan,222,251,234,255,265,248
Cairo,254,248,228,268,228,258
Giza,261,245,241,251,230,256
Ismailia,224,270,231,227,239,254
Mansoura,252,314,263,274,293,297
Port Said,243,237,232,261,231,233
Tanta,235,249,237,260,247,216

In [40]:
pd.crosstab(df['branch'], df['city'])

city,Alexandria,Aswan,Cairo,Giza,Ismailia,Mansoura,Port Said,Tanta
branch,,,,,,,,
Alexandria Main,251,222,254,261,224,252,243,235
Aswan Branch,248,251,248,245,270,314,237,249
Cairo Main,243,234,228,241,231,263,232,237
Giza Main,262,255,268,251,227,274,261,260
Mansoura Branch,227,265,228,230,239,293,231,247
Tanta Branch,242,248,258,256,254,297,233,216

In [41]:
df[df["city"].isna()]["branch"].value_counts(dropna=False)

branch
Alexandria Main    19
Cairo Main         18
Tanta Branch       18
Giza Main          16
Mansoura Branch    16
Aswan Branch       13
Name: count, dtype: int64

In [42]:
pd.crosstab(df["city"], df["loan_type"], normalize="index").round(2)

loan_type,Auto Loan,Business Loan,Education Loan,Home Improvement,Mortgage,Personal Loan
city,,,,,,
Alexandria,0.16,0.24,0.09,0.09,0.17,0.25
Aswan,0.14,0.22,0.11,0.11,0.16,0.26
Cairo,0.17,0.19,0.10,0.10,0.18,0.26
Giza,0.16,0.21,0.09,0.12,0.16,0.26
Ismailia,0.13,0.20,0.11,0.12,0.18,0.26
Mansoura,0.15,0.21,0.09,0.12,0.19,0.24
Port Said,0.15,0.22,0.09,0.11,0.18,0.25
Tanta,0.17,0.21,0.09,0.10,0.19,0.24

In [43]:
pd.crosstab(df["city"], df["application_channel"], normalize="index").round(2)

application_channel  Branch  Mobile App  Online  Relationship Manager
city
Alexandria             0.39        0.21    0.26                  0.14
Aswan                  0.38        0.20    0.26                  0.17
Cairo                  0.40        0.20    0.24                  0.15
Giza                   0.40        0.20    0.25                  0.14
Ismailia               0.40        0.21    0.24                  0.15
Mansoura               0.40        0.22    0.24                  0.14
Port Said              0.38        0.22    0.25                  0.15
Tanta                  0.37        0.21    0.24                  0.18

In [44]:
pd.crosstab(df["city"], df["employment_status"], normalize="index").round(2)

employment_status,Business Owner,Retired,Salaried,Self-Employed,Unemployed
city,,,,,
Alexandria,0.11,0.08,0.52,0.22,0.06
Aswan,0.14,0.10,0.52,0.17,0.06
Cairo,0.12,0.10,0.52,0.20,0.06
Giza,0.12,0.10,0.54,0.19,0.05
Ismailia,0.12,0.10,0.54,0.18,0.06
Mansoura,0.12,0.10,0.54,0.18,0.06
Port Said,0.12,0.11,0.53,0.18,0.06
Tanta,0.12,0.11,0.54,0.18,0.05

In [45]:
df.groupby("city")["annual_income_egp"].median().round(2)

city
Alexandria    37562.0
Aswan         36472.0
Cairo         36161.0
Giza          37073.0
Ismailia      36765.0
Mansoura      36551.0
Port Said     36436.5
Tanta         36566.0
Name: annual_income_egp, dtype: float64

In [46]:
df["city"] = df["city"].fillna("Unknown")
df["city"].value_counts(dropna=False)

city
Mansoura      1693
Cairo         1484
Giza          1484
Aswan         1475
Alexandria    1473
Ismailia      1445
Tanta         1444
Port Said     1437
Unknown        100
Name: count, dtype: int64

In [47]:
pd.crosstab([df["branch"], df["application_channel"]], df["city"], normalize="index").round(2)

city                                  Alexandria  Aswan  Cairo  Giza  \
branch          application_channel
Alexandria Main Branch                      0.14   0.10   0.14  0.13
                Mobile App                  0.10   0.12   0.15  0.13
                Online                      0.13   0.10   0.11  0.14
                Relationship Manager        0.14   0.14   0.11  0.13
Aswan Branch    Branch                      0.12   0.11   0.12  0.13
                Mobile App                  0.13   0.13   0.10  0.11
                Online                      0.11   0.13   0.13  0.12
                Relationship Manager        0.10   0.12   0.13  0.10
Cairo Main      Branch                      0.12   0.13   0.12  0.14
                Mobile App                  0.12   0.10   0.09  0.12
                Online                      0.13   0.14   0.14  0.11
                Relationship Manager        0.15   0.10   0.12  0.11
Giza Main       Branch                      0.12   0.12   0.14  0.12
                Mobile App                  0.13   0.11   0.12  0.14
                Online                      0.16   0.11   0.13  0.12
                Relationship Manager        0.10   0.16   0.11  0.11
Mansoura Branch Branch                      0.11   0.12   0.11  0.13
                Mobile App                  0.11   0.13   0.14  0.09
                Online                      0.12   0.15   0.09  0.12
                Relationship Manager        0.13   0.15   0.12  0.10
Tanta Branch    Branch                      0.12   0.12   0.13  0.11
                Mobile App                  0.14   0.10   0.10  0.13
                Online                      0.12   0.13   0.14  0.13
                Relationship Manager        0.08   0.15   0.14  0.15

city                                  Ismailia  Mansoura  Port Said  Tanta  \
branch          application_channel
Alexandria Main Branch                    0.12      0.14       0.13   0.10
                Mobile App                0.13      0.12       0.12   0.10
                Online                    0.12      0.12       0.13   0.15
                Relationship Manager      0.07      0.14       0.11   0.15
Aswan Branch    Branch                    0.14      0.16       0.10   0.11
                Mobile App                0.12      0.13       0.14   0.14
                Online                    0.12      0.16       0.11   0.11
                Relationship Manager      0.14      0.14       0.12   0.13
Cairo Main      Branch                    0.12      0.14       0.10   0.12
                Mobile App                0.13      0.16       0.13   0.14
                Online                    0.11      0.13       0.13   0.10
                Relationship Manager      0.12      0.12       0.13   0.14
Giza Main       Branch                    0.13      0.13       0.12   0.11
                Mobile App                0.08      0.15       0.13   0.15
                Online                    0.09      0.11       0.14   0.12
                Relationship Manager      0.13      0.15       0.11   0.14
Mansoura Branch Branch                    0.12      0.15       0.12   0.12
                Mobile App                0.12      0.17       0.11   0.11
                Online                    0.13      0.14       0.11   0.13
                Relationship Manager      0.11      0.11       0.13   0.15
Tanta Branch    Branch                    0.12      0.15       0.12   0.11
                Mobile App                0.14      0.16       0.12   0.10
                Online                    0.12      0.15       0.11   0.09
                Relationship Manager      0.11      0.13       0.11   0.13

city                                  Unknown
branch          application_channel
Alexandria Main Branch                   0.01
                Mobile App               0.01
                Online                   0.01
                Relationship Manager     0.01
Aswan Branch    Branch                   0.01
                Mobile App               0.00
                Online                   0.01
                Relationship Manager     0.00
Cairo Main      Branch                   0.01
                Mobile App               0.01
                Online                   0.01
                Relationship Manager     0.01
Giza Main       Branch                   0.01
                Mobile App               0.01
                Online                   0.01
                Relationship Manager     0.00
Mansoura Branch Branch                   0.01
                Mobile App               0.01
                Online                   0.01
                Relationship Manager     0.00
Tanta Branch    Branch                   0.01
                Mobile App               0.01
                Online                   0.01
                Relationship Manager     0.01

### Solving `loan_status` inconsistent formatting Issues

In [48]:
df["loan_status"] = df["loan_status"].str.strip().str.title()
df["loan_status"]

0        Defaulted
1           Active
2           Active
3           Active
4           Closed
           ...
12030    Defaulted
12031       Active
12032    Defaulted
12033       Closed
12034    Defaulted
Name: loan_status, Length: 12035, dtype: object

In [49]:
df["loan_status"].value_counts(dropna=False)

loan_status
Active          5997
Defaulted       2249
Closed          1985
Restructured    1188
Written Off      616
Name: count, dtype: int64

### Re-correcting & Solving `origination_date` tybe from object to datetime Issues

In [50]:
df["origination_date"] = pd.to_datetime(df["origination_date"])
df["origination_date"]

0       2025-01-19
1       2023-10-20
2       2019-11-26
3       2021-07-12
4       2023-08-25
           ...
12030   2019-06-24
12031   2021-09-29
12032   2022-01-08
12033   2020-06-28
12034   2025-12-21
Name: origination_date, Length: 12035, dtype: datetime64[ns]

In [51]:
df.dtypes

record_id                           int64
loan_id                            object
customer_age                      float64
city                               object
branch                             object
employment_status                  object
annual_income_egp                 float64
loan_type                          object
loan_purpose                       object
loan_amount_egp                     int64
interest_rate_pct                 float64
term_months                         int64
credit_score                      float64
debt_to_income_pct                float64
risk_grade                         object
origination_date           datetime64[ns]
application_channel                object
loan_status                        object
monthly_installment_egp           float64
remaining_balance_egp             float64
dtype: object

### Solving `customer_age` missing values Issues

In [52]:
df["customer_age"].describe().round(2)

count    12029.00
mean        43.99
std         13.47
min         18.00
25%         32.00
50%         44.00
75%         56.00
max         67.00
Name: customer_age, dtype: float64

In [53]:
df[df["customer_age"].isna()]

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
62,63,LN106709,NaN,Giza,Giza Main,Self-Employed,68274.0,Auto Loan,Business Expansion,479239,12.50,84,605.0,74.70,D,2021-08-21,Relationship Manager,Active,8588.56,422169.24
569,570,LN109623,NaN,Giza,Giza Main,Self-Employed,73475.0,Personal Loan,Vehicle Purchase,245273,12.64,60,670.0,43.93,C,2020-02-18,Mobile App,Closed,5535.63,0.00
6107,6108,LN101771,NaN,Port Said,Alexandria Main,Retired,26412.0,Mortgage,Debt Consolidation,712908,15.43,60,664.0,65.84,C,2024-06-26,Branch,Active,17121.37,277048.61
6217,6218,LN105186,NaN,Giza,Alexandria Main,Business Owner,40715.0,Business Loan,Personal Expenses,240818,12.93,12,653.0,95.00,C,2019-01-16,Online,Defaulted,21501.30,100319.56
8590,8591,LN101072,NaN,Cairo,Aswan Branch,Salaried,27148.0,Business Loan,Vehicle Purchase,153395,11.98,36,657.0,53.61,C,2025-11-29,Branch,Closed,5093.46,0.00
9845,9846,LN100661,NaN,Ismailia,Tanta Branch,Salaried,35435.0,Home Improvement,Vehicle Purchase,308233,7.43,48,624.0,52.70,D,2023-03-10,Branch,Closed,7442.67,0.00

In [54]:
df["customer_age"].median()

np.float64(44.0)

In [55]:
df["customer_age"] = df["customer_age"].fillna(df["customer_age"].median())

In [56]:
df["customer_age"].isnull().sum()

np.int64(0)

### Solving `employment_status` missing values Issues

In [57]:
df["employment_status"].value_counts(dropna=False)

employment_status
Salaried          6312
Self-Employed     2261
Business Owner    1454
Retired           1191
Unemployed         717
NaN                100
Name: count, dtype: int64

In [58]:
df[df["employment_status"].isna()][["record_id", "loan_id", "annual_income_egp", "loan_type", "loan_amount_egp", "credit_score", "risk_grade", "loan_status"]]

,record_id,loan_id,annual_income_egp,loan_type,loan_amount_egp,credit_score,risk_grade,loan_status
330,331,LN102622,77387.0,Auto Loan,503815,761.0,A,Closed
538,539,LN106203,25606.0,Mortgage,458431,629.0,D,Defaulted
838,839,LN107483,44001.0,Business Loan,817607,670.0,C,Active
840,841,LN108116,52794.0,Education Loan,196091,713.0,B,Restructured
913,914,LN109683,31295.0,Business Loan,285445,716.0,B,Closed
...,...,...,...,...,...,...,...,...
11694,11695,LN101622,16280.0,Home Improvement,134905,776.0,A,Closed
11705,11706,LN103719,41077.0,Auto Loan,125549,638.0,D,Active
11770,11771,LN107775,31285.0,Personal Loan,122629,709.0,B,Active
11862,11863,LN111947,38389.0,Mortgage,965032,533.0,E,Defaulted
11918,11919,LN108402,60307.0,Education Loan,255719,613.0,D,Active

In [59]:
df["employment_status"].mode()

0    Salaried
Name: employment_status, dtype: object

In [60]:
# Missing values in employment_status were replaced using the mode of the column (Salaried).

df["employment_status"] = df["employment_status"].fillna(df["employment_status"].mode()[0])
df["employment_status"].isna().sum()

np.int64(0)

### Solving `annual_income_egp` missing values Issues

In [61]:
df["annual_income_egp"].describe().round(2)

count     11935.00
mean      42460.33
std       25135.19
min        4199.00
25%       25238.50
50%       36566.00
75%       52919.50
max      250000.00
Name: annual_income_egp, dtype: float64

In [62]:
df[df["annual_income_egp"].isna()]["employment_status"].value_counts()

employment_status
Salaried          48
Self-Employed     17
Business Owner    13
Unemployed        12
Retired           10
Name: count, dtype: int64

In [63]:
# Missing values in annual_income_egp will be replaced using the median Imputation

df["annual_income_egp"] = df["annual_income_egp"].fillna(df["annual_income_egp"].median())
df["annual_income_egp"].isna().sum()

np.int64(0)

### Solving `loan_purpose` missing value Issues

In [64]:
df["loan_purpose"].value_counts(dropna=False)

loan_purpose
Medical               1895
Personal Expenses     1708
Education             1697
Business Expansion    1691
Home Purchase         1676
Vehicle Purchase      1654
Debt Consolidation    1614
NaN                    100
Name: count, dtype: int64

In [65]:
pd.crosstab(df["loan_purpose"], df["loan_type"], normalize="index").round(2)

loan_type,Auto Loan,Business Loan,Education Loan,Home Improvement,Mortgage,Personal Loan
loan_purpose,,,,,,
Business Expansion,0.15,0.21,0.10,0.09,0.18,0.26
Debt Consolidation,0.15,0.21,0.09,0.10,0.19,0.26
Education,0.15,0.23,0.11,0.11,0.18,0.23
Home Purchase,0.15,0.21,0.09,0.12,0.16,0.26
Medical,0.16,0.22,0.09,0.11,0.17,0.25
Personal Expenses,0.16,0.22,0.10,0.10,0.18,0.24
Vehicle Purchase,0.16,0.19,0.08,0.12,0.18,0.26

In [66]:
pd.crosstab(df["loan_type"], df["loan_purpose"], normalize="index").round(2)

loan_purpose,Business Expansion,Debt Consolidation,Education,Home Purchase,Medical,Personal Expenses,Vehicle Purchase
loan_type,,,,,,,
Auto Loan,0.14,0.13,0.14,0.14,0.16,0.14,0.14
Business Loan,0.14,0.14,0.15,0.14,0.17,0.14,0.12
Education Loan,0.15,0.13,0.16,0.14,0.15,0.15,0.12
Home Improvement,0.12,0.12,0.14,0.16,0.16,0.14,0.16
Mortgage,0.14,0.15,0.15,0.13,0.15,0.15,0.14
Personal Loan,0.15,0.14,0.13,0.15,0.16,0.14,0.14

In [67]:
df[df["loan_purpose"].isna()][["loan_type", "loan_amount_egp", "annual_income_egp", "credit_score", "loan_status"]].describe(include="all")

,loan_type,loan_amount_egp,annual_income_egp,credit_score,loan_status
count,100,1.000000e+02,100.000000,100.00000,100
unique,6,NaN,NaN,NaN,5
top,Personal Loan,NaN,NaN,NaN,Active
freq,29,NaN,NaN,NaN,46
mean,NaN,3.628693e+05,43115.120000,680.95000,NaN
std,NaN,4.756663e+05,24173.716845,70.62025,NaN
min,NaN,6.151000e+03,9481.000000,517.00000,NaN
25%,NaN,7.945125e+04,25741.750000,631.00000,NaN
50%,NaN,1.551355e+05,37230.000000,681.50000,NaN
75%,NaN,4.677548e+05,57419.000000,720.25000,NaN
max,NaN,2.392811e+06,124022.000000,850.00000,NaN

In [68]:
df["loan_purpose"] = df["loan_purpose"].fillna("Unknown")
df["loan_purpose"].isna().sum()

np.int64(0)

In [69]:
df["loan_purpose"].value_counts(dropna=False)

loan_purpose
Medical               1895
Personal Expenses     1708
Education             1697
Business Expansion    1691
Home Purchase         1676
Vehicle Purchase      1654
Debt Consolidation    1614
Unknown                100
Name: count, dtype: int64

### Solving `interest_rate_pct` missing values , 0.00 value Issues

In [70]:
df["interest_rate_pct"].describe().round(2)

count    11935.00
mean        13.02
std          3.73
min          0.00
25%          9.83
50%         13.06
75%         16.23
max         19.50
Name: interest_rate_pct, dtype: float64

In [71]:
df[df["interest_rate_pct"].isna()]["loan_type"].value_counts()

loan_type
Business Loan       35
Mortgage            22
Personal Loan       17
Auto Loan           11
Home Improvement    10
Education Loan       5
Name: count, dtype: int64

In [72]:
df.groupby("loan_type")["interest_rate_pct"].median().round(2)

loan_type
Auto Loan           12.99
Business Loan       13.07
Education Loan      13.40
Home Improvement    12.93
Mortgage            13.05
Personal Loan       13.06
Name: interest_rate_pct, dtype: float64

In [73]:
# Impute Missing "Interest Rate" values using the "Group-wise" Median based on "Loan Type"

df["interest_rate_pct"] = df["interest_rate_pct"].fillna(df.groupby("loan_type")["interest_rate_pct"].transform("median"))
df["interest_rate_pct"].isna().sum()

np.int64(0)

In [74]:
df["interest_rate_pct"].describe().round(2)

count    12035.00
mean        13.02
std          3.72
min          0.00
25%          9.86
50%         13.06
75%         16.20
max         19.50
Name: interest_rate_pct, dtype: float64

In [75]:
df[df["interest_rate_pct"] == 0]

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
2677,2678,LN111911,22.0,Port Said,Mansoura Branch,Salaried,13833.0,Mortgage,Medical,369282,0.0,72,636.0,95.0,D,2023-06-12,Mobile App,Restructured,7281.13,309358.76

In [76]:
df[df["interest_rate_pct"] <= 1]

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
2677,2678,LN111911,22.0,Port Said,Mansoura Branch,Salaried,13833.0,Mortgage,Medical,369282,0.0,72,636.0,95.0,D,2023-06-12,Mobile App,Restructured,7281.13,309358.76

In [77]:
# Potential anomaly — retained because there is insufficient evidence to confirm it as an error

df[(df["interest_rate_pct"] == 0) & (df["interest_rate_pct"] <= 1)]

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
2677,2678,LN111911,22.0,Port Said,Mansoura Branch,Salaried,13833.0,Mortgage,Medical,369282,0.0,72,636.0,95.0,D,2023-06-12,Mobile App,Restructured,7281.13,309358.76

### Solving `credit_score` missing values Issues

In [78]:
df["credit_score"].describe().round(2)

count    11935.00
mean       675.70
std         73.96
min        363.00
25%        625.00
50%        677.00
75%        726.00
max        850.00
Name: credit_score, dtype: float64

In [79]:
df[df["credit_score"].isna()]["risk_grade"].value_counts()

risk_grade
C    28
D    21
E    18
B    17
A    16
Name: count, dtype: int64

In [80]:
df.groupby("risk_grade")["credit_score"].median()

risk_grade
A    780.0
B    722.0
C    675.5
D    627.0
E    570.0
Name: credit_score, dtype: float64

In [81]:
# Impute Missing "Credit Score" values using the "Group-wise" Median based on "Risk Grade"

df["credit_score"] = df["credit_score"].fillna(df.groupby("risk_grade")["credit_score"].transform("median"))
df["credit_score"].isna().sum()

np.int64(0)

In [82]:
df.isna().sum()

record_id                  0
loan_id                    0
customer_age               0
city                       0
branch                     0
employment_status          0
annual_income_egp          0
loan_type                  0
loan_purpose               0
loan_amount_egp            0
interest_rate_pct          0
term_months                0
credit_score               0
debt_to_income_pct         0
risk_grade                 0
origination_date           0
application_channel        0
loan_status                0
monthly_installment_egp    0
remaining_balance_egp      0
dtype: int64

### Solving `loan_id` Duplicate Values Issues

In [83]:
df["loan_id"].duplicated().sum()

np.int64(70)

In [84]:
df[df["loan_id"].duplicated(keep=False)].sort_values("loan_id")

,record_id,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
10394,10395,LN100012,56.0,Alexandria,Aswan Branch,Retired,13275.0,Education Loan,Education,77496,7.95,60,734.0,31.54,B,2021-09-05,Branch,Closed,1569.49,0.00
10429,10430,LN100012,56.0,Alexandria,Aswan Branch,Retired,13275.0,Education Loan,Education,77496,7.95,60,734.0,31.54,B,2021-09-05,Branch,Closed,1569.49,0.00
11090,11091,LN100191,62.0,Aswan,Cairo Main,Unemployed,43729.0,Personal Loan,Business Expansion,80499,7.26,240,624.0,57.31,D,2025-03-16,Mobile App,Restructured,636.74,34658.92
7162,7163,LN100191,62.0,Aswan,Cairo Main,Unemployed,43729.0,Personal Loan,Business Expansion,80499,7.26,240,624.0,57.31,D,2025-03-16,Mobile App,Restructured,636.74,34658.92
6564,6565,LN100247,53.0,Aswan,Giza Main,Self-Employed,30954.0,Business Loan,Education,222822,16.26,36,723.0,48.24,B,2025-05-19,Online,Closed,7862.38,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6871,6872,LN111237,38.0,Giza,Alexandria Main,Salaried,15544.0,Auto Loan,Home Purchase,112095,12.61,72,796.0,76.27,A,2024-03-16,Mobile App,Defaulted,2227.19,60484.51
9916,9917,LN111279,46.0,Cairo,Tanta Branch,Salaried,48514.0,Home Improvement,Medical,369667,14.09,180,675.0,38.02,C,2020-08-15,Branch,Closed,4945.38,0.00
9185,9186,LN111279,46.0,Cairo,Tanta Branch,Salaried,48514.0,Home Improvement,Medical,369667,14.09,180,675.0,38.02,C,2020-08-15,Branch,Closed,4945.38,0.00
81,82,LN111813,43.0,Cairo,Aswan Branch,Salaried,32577.0,Home Improvement,Personal Expenses,282666,19.27,60,638.0,63.68,D,2024-03-18,Relationship Manager,Defaulted,7374.58,170429.63
4186,4187,LN111813,43.0,Cairo,Aswan Branch,Salaried,32577.0,Home Improvement,Personal Expenses,282666,19.27,60,638.0,63.68,D,2024-03-18,Relationship Manager,Defaulted,7374.58,170429.63

In [85]:
df.duplicated().sum()

np.int64(0)

In [86]:
df[df["loan_id"].duplicated(keep=False)].drop(columns=["record_id"]).duplicated().sum()

np.int64(64)

In [87]:
duplicate_loans = df[df["loan_id"].duplicated(keep=False)].drop(columns=["record_id"])

different_duplicate_loans = duplicate_loans.groupby("loan_id").filter(lambda g: len(g.drop_duplicates()) > 1)

different_duplicate_loans.sort_values("loan_id")

,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
3537,LN100921,54.0,Aswan,Aswan Branch,Business Owner,23440.0,Mortgage,Home Purchase,366688,10.51,36,603.0,85.08,D,2021-10-21,Mobile App,Defaulted,11919.99,290359.51
10127,LN100921,54.0,Aswan,Aswan Branch,Business Owner,36566.0,Mortgage,Home Purchase,366688,10.51,36,603.0,85.08,D,2021-10-21,Mobile App,Defaulted,11919.99,290359.51
2039,LN102338,29.0,Port Said,Cairo Main,Unemployed,23185.0,Business Loan,Vehicle Purchase,346232,8.83,120,722.0,22.66,B,2021-05-28,Online,Active,4354.13,285222.44
9574,LN102338,29.0,Port Said,Cairo Main,Unemployed,36566.0,Business Loan,Vehicle Purchase,346232,8.83,120,722.0,22.66,B,2021-05-28,Online,Active,4354.13,285222.44
4945,LN110231,36.0,Giza,Mansoura Branch,Salaried,30587.0,Business Loan,Vehicle Purchase,217499,13.30,60,683.0,50.40,C,2022-10-07,Branch,Active,4982.25,131073.69
5798,LN110231,36.0,Giza,Mansoura Branch,Retired,30587.0,Business Loan,Vehicle Purchase,217499,13.30,60,683.0,50.40,C,2022-10-07,Branch,Active,4982.25,131073.69
966,LN110619,46.0,Unknown,Cairo Main,Salaried,34282.0,Personal Loan,Medical,75209,15.90,24,761.0,61.69,A,2023-12-25,Mobile App,Active,3678.86,48406.35
7283,LN110619,46.0,Port Said,Cairo Main,Salaried,34282.0,Personal Loan,Medical,75209,15.90,24,761.0,61.69,A,2023-12-25,Mobile App,Active,3678.86,48406.35
358,LN110932,59.0,Alexandria,Cairo Main,Self-Employed,36566.0,Personal Loan,Home Purchase,32135,17.57,120,667.0,69.00,C,2025-08-04,Relationship Manager,Defaulted,570.15,27373.23
7520,LN110932,59.0,Alexandria,Cairo Main,Self-Employed,32320.0,Personal Loan,Home Purchase,32135,17.57,120,667.0,69.00,C,2025-08-04,Relationship Manager,Defaulted,570.15,27373.23
6462,LN111139,61.0,Unknown,Cairo Main,Self-Employed,32271.0,Auto Loan,Medical,135433,18.59,36,682.0,79.30,C,2022-03-17,Branch,Active,4936.40,81248.00
7802,LN111139,61.0,Giza,Cairo Main,Self-Employed,32271.0,Auto Loan,Medical,135433,18.59,36,682.0,79.30,C,2022-03-17,Branch,Active,4936.40,81248.00

In [88]:
# Restore the original value for the six duplicate loan records
# where the difference was caused by our previous imputation

df.loc[(df["loan_id"] == "LN100921") & (df["annual_income_egp"] == 36566), "annual_income_egp"] = 23440

df.loc[(df["loan_id"] == "LN102338") & (df["annual_income_egp"] == 36566), "annual_income_egp"] = 23185

df.loc[(df["loan_id"] == "LN110932") & (df["annual_income_egp"] == 36566), "annual_income_egp"] = 32320

df.loc[(df["loan_id"] == "LN110231") & (df["employment_status"] == "Salaried"), "employment_status"] = "Retired"

df.loc[(df["loan_id"] == "LN110619") & (df["city"] == "Unknown"), "city"] = "Port Said"

df.loc[(df["loan_id"] == "LN111139") & (df["city"] == "Unknown"), "city"] = "Giza"

In [89]:
df[df["loan_id"].duplicated(keep=False)].drop(columns=["record_id"]).duplicated().sum()

np.int64(70)

##### **Duplicate validation note:**
During the cleaning process, 70 unique `loan_id` values were found to have duplicates, representing 140 rows. A comparison with the original dataset showed 8 missing cells within these duplicated records: 2 in `city`, 1 in `employment_status`, 3 in `annual_income_egp`, and 2 in `loan_purpose`. Six of these missing values were present in only one record of a duplicated `loan_id`, so the imputation temporarily created differences between otherwise duplicated records.
These 6 values were restored using the corresponding original values from their duplicate records. The remaining 2 missing `loan_purpose` values were missing in both duplicated records, so replacing both with `Unknown` preserved their consistency.
The duplicate records were then rechecked, confirming that the imputation-related differences had been resolved without requiring the cleaning process to be repeated.

In [90]:
df["loan_id"].value_counts().value_counts()

count
1    11895
2       70
Name: count, dtype: int64

In [91]:
duplicate_rows = df[df["loan_id"].duplicated(keep=False)]

duplicate_rows.drop(columns=["record_id"]).duplicated().sum()

np.int64(70)

In [92]:
id_columns = ["loan_id"]

duplicate_rows.groupby("loan_id").size().value_counts()

2    70
Name: count, dtype: int64

##### **Duplicate records handling note:**
The duplicate `loan_id` investigation identified 70 duplicated loan IDs, each appearing exactly twice. After validating the records and excluding the `record_id` column, the duplicated records were found to contain identical loan information. Since `record_id` is only a record identifier and does not represent different loan information, one copy of each duplicated `loan_id` can be retained and the redundant duplicate record can be removed.

In [93]:
# Remove redundant duplicate loan records
df = df.drop_duplicates(subset="loan_id", keep="first")

# Remove the record-id identifier
df = df.drop(columns="record_id")

# Reset the DataFrame index
df = df.reset_index(drop=True)

### Final Data Quality Check & Validation

In [94]:
df.shape

(11965, 19)

In [95]:
df

,loan_id,customer_age,city,branch,employment_status,annual_income_egp,loan_type,loan_purpose,loan_amount_egp,interest_rate_pct,term_months,credit_score,debt_to_income_pct,risk_grade,origination_date,application_channel,loan_status,monthly_installment_egp,remaining_balance_egp
0,LN109160,32.0,Aswan,Mansoura Branch,Salaried,34141.0,Mortgage,Education,1155415,10.64,36,555.0,95.00,E,2025-01-19,Relationship Manager,Defaulted,37630.14,431740.31
1,LN101801,66.0,Aswan,Aswan Branch,Salaried,34631.0,Education Loan,Medical,22238,7.22,36,514.0,57.15,E,2023-10-20,Branch,Active,688.87,17359.26
2,LN102666,29.0,Port Said,Mansoura Branch,Self-Employed,49700.0,Education Loan,Medical,236672,11.75,120,725.0,25.27,B,2019-11-26,Online,Active,3361.43,113965.42
3,LN102617,43.0,Giza,Giza Main,Salaried,14385.0,Business Loan,Education,183922,16.34,60,629.0,82.46,D,2021-07-12,Branch,Active,4505.91,108513.48
4,LN110048,61.0,Ismailia,Cairo Main,Business Owner,19550.0,Mortgage,Medical,182772,6.58,72,756.0,55.46,A,2023-08-25,Mobile App,Closed,3079.35,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11960,LN101585,40.0,Port Said,Mansoura Branch,Business Owner,24620.0,Mortgage,Vehicle Purchase,702270,13.72,24,646.0,95.00,D,2019-06-24,Branch,Defaulted,33625.19,207614.90
11961,LN100815,26.0,Cairo,Cairo Main,Business Owner,34997.0,Personal Loan,Business Expansion,125619,10.29,72,699.0,55.96,C,2021-09-29,Online,Active,2345.61,96448.47
11962,LN104280,67.0,Port Said,Giza Main,Salaried,23052.0,Auto Loan,Debt Consolidation,158763,16.58,84,637.0,77.08,D,2022-01-08,Online,Defaulted,3206.02,116719.89
11963,LN104089,64.0,Mansoura,Aswan Branch,Salaried,16718.0,Auto Loan,Home Purchase,121521,10.71,240,700.0,17.87,B,2020-06-28,Relationship Manager,Closed,1230.43,0.00
11964,LN100336,49.0,Giza,Cairo Main,Salaried,31096.0,Mortgage,Home Purchase,791651,7.46,36,727.0,95.00,B,2025-12-21,Online,Defaulted,24610.74,382423.96

In [96]:
df.isna().sum()

loan_id                    0
customer_age               0
city                       0
branch                     0
employment_status          0
annual_income_egp          0
loan_type                  0
loan_purpose               0
loan_amount_egp            0
interest_rate_pct          0
term_months                0
credit_score               0
debt_to_income_pct         0
risk_grade                 0
origination_date           0
application_channel        0
loan_status                0
monthly_installment_egp    0
remaining_balance_egp      0
dtype: int64

In [97]:
df["loan_id"].duplicated().sum()

np.int64(0)

In [98]:
df.dtypes

loan_id                            object
customer_age                      float64
city                               object
branch                             object
employment_status                  object
annual_income_egp                 float64
loan_type                          object
loan_purpose                       object
loan_amount_egp                     int64
interest_rate_pct                 float64
term_months                         int64
credit_score                      float64
debt_to_income_pct                float64
risk_grade                         object
origination_date           datetime64[ns]
application_channel                object
loan_status                        object
monthly_installment_egp           float64
remaining_balance_egp             float64
dtype: object

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11965 entries, 0 to 11964
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  11965 non-null  object
 1   customer_age             11965 non-null  float64
 2   city                     11965 non-null  object
 3   branch                   11965 non-null  object
 4   employment_status        11965 non-null  object
 5   annual_income_egp        11965 non-null  float64
 6   loan_type                11965 non-null  object
 7   loan_purpose             11965 non-null  object
 8   loan_amount_egp          11965 non-null  int64
 9   interest_rate_pct        11965 non-null  float64
 10  term_months              11965 non-null  int64
 11  credit_score             11965 non-null  float64
 12  debt_to_income_pct       11965 non-null  float64
 13  risk_grade               11965 non-null  object
 14  origination_date         11965 non-null  datetime64[ns]
 15  application_channel      11965 non-null  object
 16  loan_status              11965 non-null  object
 17  monthly_installment_egp  11965 non-null  float64
 18  remaining_balance_egp    11965 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(2), object(9)
memory usage: 1.7+ MB

## Analysis & Visualization

This section analyzes the cleaned Banking Loans dataset to identify key patterns and relationships across loan characteristics, customer profiles, credit risk, financial exposure, geographic distribution, and loan origination trends.

The analysis questions were defined before implementation to ensure that each question addresses a meaningful aspect of the dataset and is supported by an appropriate visualization.

### Q1. What is the distribution of customer ages?

In [120]:
customer_age_stats = df["customer_age"].describe().round(2)
customer_age_stats

count    11965.00
mean        43.98
std         13.47
min         18.00
25%         32.00
50%         44.00
75%         56.00
max         67.00
Name: customer_age, dtype: float64

**Answer:** Customer ages range from 18 to 67 years, with an average age of 43.98 years and a median of 44 years. The middle 50% of customers are between 32 and 56 years old.

In [138]:
fig = px.histogram(df, y="customer_age", labels={"customer_age": "Customer Age", "count": "Number of Customers"}, title="Distribution of Customer Ages", orientation="h")

fig.update_traces(ybins=dict(size=1), texttemplate="%{x}", textposition="outside")

fig.update_layout(height=900, margin=dict(l=80, r=100, t=80, b=80), bargap=0.05)

fig.show()

### Q2 — What is the distribution of annual income?

In [140]:
annual_income_stats = df["annual_income_egp"].describe().round(2)
annual_income_stats

count     11965.00
mean      42426.21
std       25067.30
min        4199.00
25%       25306.00
50%       36566.00
75%       52699.00
max      250000.00
Name: annual_income_egp, dtype: float64

**Answer:** Annual customer income ranges from **4,199 EGP** to **250,000 EGP**, with an average annual income of **42,426.21 EGP** and a median of **36,566 EGP**. The middle 50% of customers have annual incomes between **25,306 EGP** and **52,699 EGP**.

In [149]:
fig = px.histogram(df, x="annual_income_egp",
                    nbins=20,
                    labels={"annual_income_egp": "Annual Income (EGP)", "count": "Number of Customers"},
                    title="Distribution of Annual Customer Income")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=900, margin=dict(l=80, r=100, t=80, b=80), bargap=0.05)

fig.show()

### Q3. What is the distribution of loan amounts?

In [142]:
loan_amount_stats = df["loan_amount_egp"].describe().round(2)
loan_amount_stats

count      11965.00
mean      371157.92
std       495861.17
min         5000.00
25%        83729.00
50%       188317.00
75%       454481.00
max      5000000.00
Name: loan_amount_egp, dtype: float64

**Answer:** Loan amounts range from **5,000 EGP** to **5,000,000 EGP**, with an average loan amount of **371,157.92 EGP** and a median of **188,317 EGP**. The middle 50% of loans are between **83,729 EGP** and **454,481 EGP**.

In [148]:
fig = px.histogram(df, x="loan_amount_egp", nbins=20, labels={"loan_amount_egp": "Loan Amount (EGP)", "count": "Number of Loans"}, title="Distribution of Loan Amounts")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80), bargap=0.05)

fig.show()

### Q4. What is the distribution of credit scores?

In [150]:
credit_score_stats = df["credit_score"].describe().round(2)
credit_score_stats

count    11965.00
mean       675.65
std         73.95
min        363.00
25%        625.00
50%        677.00
75%        726.00
max        850.00
Name: credit_score, dtype: float64

**Answer:** Credit scores range from **363** to **850**, with an average credit score of **675.65** and a median of **677**. The middle 50% of customers have credit scores between **625** and **726**.

In [151]:
fig = px.histogram(df, x="credit_score", nbins=20, labels={"credit_score": "Credit Score", "count": "Number of Customers"}, title="Distribution of Credit Scores")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80), bargap=0.05)

fig.show()

### Q5. What is the distribution of debt-to-income ratios?

In [152]:
debt_to_income_stats = df["debt_to_income_pct"].describe().round(2)
debt_to_income_stats

count    11965.00
mean        54.33
std         24.54
min          5.52
25%         34.45
50%         54.28
75%         73.08
max         95.00
Name: debt_to_income_pct, dtype: float64

**Answer:** Debt-to-income ratios range from **5.52%** to **95%**, with an average ratio of **54.33%** and a median of **54.28%**. The middle 50% of customers have debt-to-income ratios between **34.45%** and **73.08%**.

In [164]:
fig = px.histogram(df, x="debt_to_income_pct",
                   labels={"debt_to_income_pct": "Debt-to-Income Ratio (%)", "count": "Number of Customers"},
                   title="Distribution of Debt-to-Income Ratios")

fig.update_traces(xbins=dict(start=5, end=100, size=5), texttemplate="%{y}", textposition="outside")

fig.update_xaxes(ticksuffix="%")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80), bargap=0.05)

fig.show()

### Q6. What is the distribution of interest rates?

In [165]:
interest_rate_stats = df["interest_rate_pct"].describe().round(2)
interest_rate_stats

count    11965.00
mean        13.02
std          3.72
min          0.00
25%          9.86
50%         13.06
75%         16.20
max         19.50
Name: interest_rate_pct, dtype: float64

**Answer:** Interest rates range from **0%** to **19.50%**, with an average interest rate of **13.02%** and a median of **13.06%**. The middle 50% of loans have interest rates between **9.86%** and **16.20%**.

In [166]:
fig = px.histogram(df, x="interest_rate_pct",
                   nbins=20,
                   labels={"interest_rate_pct": "Interest Rate (%)", "count": "Number of Loans"},
                   title="Distribution of Interest Rates")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_xaxes(ticksuffix="%")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80), bargap=0.05)

fig.show()

### Q7. What is the distribution of loans by loan term?

In [173]:
loan_term_stats = df["term_months"].value_counts().sort_index()
loan_term_stats

term_months
12      714
24      950
36     1775
48      975
60     2180
72     1404
84      962
120    1247
180     862
240     896
Name: count, dtype: int64

**Answer:** Loan terms range from **12 to 240 months**. The most common loan term is **60 months**, with **2,180 loans**, while the least common term is **12 months**, with **714 loans**.

In [168]:
fig = px.bar(loan_term_stats.reset_index(),
             x="term_months",
             y="count",
             labels={"term_months": "Loan Term (Months)", "count": "Number of Loans"},
             title="Distribution of Loans by Loan Term")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q8. What is the distribution of loans by loan status?

In [174]:
loan_status_stats = df["loan_status"].value_counts().sort_values(ascending=False)
loan_status_stats

loan_status
Active          5968
Defaulted       2234
Closed          1973
Restructured    1177
Written Off      613
Name: count, dtype: int64

**Answer:** **Active** loans have the highest count with **5,968 loans**, followed by **Defaulted** loans with **2,234 loans** and **Closed** loans with **1,973 loans**. **Restructured** loans account for **1,177 loans**, while **Written Off** loans have the lowest count with **613 loans**.

In [175]:
fig = px.bar(loan_status_stats.reset_index(),
            x="loan_status",
            y="count",
            labels={"loan_status": "Loan Status", "count": "Number of Loans"},
            title="Distribution of Loans by Loan Status")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q9. What is the distribution of loans by loan type?

In [176]:
loan_type_stats = df["loan_type"].value_counts().sort_values(ascending=False)
loan_type_stats

loan_type
Personal Loan       3019
Business Loan       2547
Mortgage            2123
Auto Loan           1836
Home Improvement    1278
Education Loan      1162
Name: count, dtype: int64

**Answer:** **Personal Loan** is the most common loan type with **3,019 loans**, followed by **Business Loan** with **2,547 loans** and **Mortgage** with **2,123 loans**. **Auto Loan** accounts for **1,836 loans**, while **Home Improvement** and **Education Loan** have **1,278** and **1,162 loans**, respectively.

In [177]:
fig = px.bar(loan_type_stats.reset_index(),
            x="loan_type",
            y="count",
            labels={"loan_type": "Loan Type", "count": "Number of Loans"},
            title="Distribution of Loans by Loan Type")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q10. What is the distribution of loans by risk grade?

In [178]:
risk_grade_stats = df["risk_grade"].value_counts().sort_values(ascending=False)
risk_grade_stats

risk_grade
C    3085
B    2570
D    2504
A    1956
E    1850
Name: count, dtype: int64

**Answer:** **Grade C** has the highest number of loans with **3,085 loans**, followed by **Grade B** with **2,570 loans** and **Grade D** with **2,504 loans**. **Grade A** accounts for **1,956 loans**, while **Grade E** has the lowest count with **1,850 loans**.

In [179]:
fig = px.bar(risk_grade_stats.reset_index(),
            x="risk_grade",
            y="count",
            labels={"risk_grade": "Risk Grade", "count": "Number of Loans"},
            title="Distribution of Loans by Risk Grade")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q11. How does loan amount vary with annual income?

In [180]:
loan_income_corr = df["annual_income_egp"].corr(df["loan_amount_egp"])
loan_income_corr

np.float64(0.42589757345627355)

**Answer:** The correlation between annual income and loan amount is **0.43**, indicating a **moderate positive relationship**. In general, customers with higher annual incomes tend to have higher loan amounts.

In [181]:
fig = px.scatter(df,
                x="annual_income_egp",
                y="loan_amount_egp",
                labels={"annual_income_egp": "Annual Income (EGP)", "loan_amount_egp": "Loan Amount (EGP)"},
                title="Loan Amount vs. Annual Income")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q12. How does credit score relate to debt-to-income ratio?

In [182]:
credit_dti_corr = df["credit_score"].corr(df["debt_to_income_pct"])
credit_dti_corr

np.float64(-0.0066299761560230696)

**Answer:** The correlation between credit score and debt-to-income ratio is **-0.01**, indicating a **negligible negative linear relationship**. This suggests that there is almost no linear relationship between credit scores and debt-to-income ratios in the dataset.

In [183]:
fig = px.scatter(df,
                x="credit_score",
                y="debt_to_income_pct",
                labels={"credit_score": "Credit Score", "debt_to_income_pct": "Debt-to-Income Ratio (%)"},
                title="Credit Score vs. Debt-to-Income Ratio")

fig.update_xaxes(ticksuffix="")

fig.update_yaxes(ticksuffix="%")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q13. How does loan amount vary across loan types?

In [184]:
loan_type_amount_stats = df.groupby("loan_type")["loan_amount_egp"].agg(["count", "mean", "median", "min", "max"]).round(2)
loan_type_amount_stats

                  count        mean    median    min      max
loan_type
Auto Loan          1836   193374.36  154142.0   9507  1172252
Business Loan      2547   470346.91  378762.0  15147  4298465
Education Loan     1162   139421.71  108421.0   5000  1058657
Home Improvement   1278   225953.85  176450.0  11959  1360914
Mortgage           2123  1015438.26  812775.0  53587  5000000
Personal Loan      3019    93190.83   74013.0   5000   915099

**Answer:** **Mortgage** loans have the highest average loan amount at **1,015,438.26 EGP**, followed by **Business Loans** at **470,346.91 EGP**. **Personal Loans** have the lowest average loan amount at **93,190.83 EGP**. The median values show a similar pattern across the loan types.

In [185]:
fig = px.box(df,
            x="loan_type",
            y="loan_amount_egp",
            labels={"loan_type": "Loan Type", "loan_amount_egp": "Loan Amount (EGP)"},
            title="Loan Amount Distribution Across Loan Types")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q14. How does loan amount vary across loan statuses?

In [186]:
loan_status_amount_stats = df.groupby("loan_status")["loan_amount_egp"].agg(["count", "mean", "median", "min", "max"]).round(2)
loan_status_amount_stats

              count       mean    median   min      max
loan_status
Active         5968  321970.43  164484.0  5000  5000000
Closed         1973  303083.10  157766.0  5000  4120885
Defaulted      2234  479906.92  260988.5  5094  5000000
Restructured   1177  476430.97  267233.0  6289  5000000
Written Off     613  470686.34  266543.0  6151  5000000

**Answer:** **Defaulted** loans have the highest average loan amount at **479,906.92 EGP**, followed by **Restructured** loans at **476,430.97 EGP** and **Written Off** loans at **470,686.34 EGP**. **Closed** loans have the lowest average loan amount at **303,083.10 EGP**.

In [187]:
fig = px.box(df,
            x="loan_status",
            y="loan_amount_egp",
            labels={"loan_status": "Loan Status", "loan_amount_egp": "Loan Amount (EGP)"},
            title="Loan Amount Distribution Across Loan Statuses")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q15. How does credit score vary across risk grades?

In [188]:
risk_grade_credit_stats = df.groupby("risk_grade")["credit_score"].agg(["count", "mean", "median", "min", "max"]).round(2)
risk_grade_credit_stats

            count    mean  median    min    max
risk_grade
A            1956  786.06   780.0  677.0  850.0
B            2570  722.60   722.0  677.0  749.0
C            3085  674.89   675.5  650.0  699.0
D            2504  626.42   627.0  600.0  677.0
E            1850  561.61   570.0  363.0  677.0

**Answer:** Credit scores vary clearly across risk grades. **Grade A** has the highest average credit score at **786.06**, while **Grade E** has the lowest average at **561.61**. The average credit score decreases progressively from **Grade A to Grade E**.

In [190]:
fig = px.box(df,
            x="risk_grade",
            y="credit_score",
            category_orders={"risk_grade": ["A", "B", "C", "D", "E"]},
            labels={"risk_grade": "Risk Grade", "credit_score": "Credit Score"},
            title="Credit Score Distribution Across Risk Grades")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q16. How does interest rate vary across risk grades?

In [191]:
risk_grade_interest_stats = df.groupby("risk_grade")["interest_rate_pct"].agg(["count", "mean", "median", "min", "max"]).round(2)
risk_grade_interest_stats

            count   mean  median   min    max
risk_grade
A            1956  13.03   13.06  6.51  19.49
B            2570  12.96   13.06  6.50  19.50
C            3085  13.01   13.05  6.51  19.50
D            2504  13.12   13.12  0.00  19.49
E            1850  12.99   13.05  6.50  19.50

**Answer:** Interest rates are very similar across the risk grades, with average rates ranging from **12.96%** for **Grade B** to **13.12%** for **Grade D**. This indicates that there is **very little variation in average interest rates across risk grades** in the dataset.

In [192]:
fig = px.box(df,
            x="risk_grade",
            y="interest_rate_pct",
            category_orders={"risk_grade": ["A", "B", "C", "D", "E"]},
            labels={"risk_grade": "Risk Grade", "interest_rate_pct": "Interest Rate (%)"},
            title="Interest Rate Distribution Across Risk Grades")

fig.update_yaxes(ticksuffix="%")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q17. How does average loan amount vary across employment statuses?

In [193]:
employment_loan_stats = df.groupby("employment_status")["loan_amount_egp"].agg(["count", "mean", "median", "min", "max"]).round(2)
employment_loan_stats

                   count       mean    median   min      max
employment_status
Business Owner      1443  374316.06  182772.0  8444  4405381
Retired             1185  382373.05  194032.0  5000  5000000
Salaried            6378  375796.20  188695.5  5000  5000000
Self-Employed       2247  355470.43  185497.0  5094  4120885
Unemployed           712  354050.77  184806.0  9371  5000000

**Answer:** The average loan amount is relatively similar across employment statuses, ranging from **354,050.77 EGP** for **Unemployed** customers to **382,373.05 EGP** for **Retired** customers. **Retired** customers have the highest average loan amount, while **Unemployed** customers have the lowest.

In [215]:
fig = px.bar(employment_loan_stats.reset_index(),
            x="employment_status",
            y="mean",
            labels={"employment_status": "Employment Status", "mean": "Average Loan Amount (EGP)"},
            title="Average Loan Amount Across Employment Statuses")

fig.update_traces(texttemplate="%{y:.2f}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q18. How does average annual income vary across loan types?

In [195]:
loan_type_income_stats = df.groupby("loan_type")["annual_income_egp"].agg(["count", "mean", "median", "min", "max"]).round(2)
loan_type_income_stats

                  count      mean   median     min       max
loan_type
Auto Loan          1836  43289.41  36895.5  7181.0  232713.0
Business Loan      2547  42302.80  36566.0  4918.0  221272.0
Education Loan     1162  42599.15  36566.0  5888.0  204277.0
Home Improvement   1278  41971.94  36566.0  5011.0  221520.0
Mortgage           2123  42308.67  36566.0  4199.0  250000.0
Personal Loan      3019  42213.78  36230.0  4402.0  250000.0

**Answer:** Average annual income is relatively similar across all loan types, ranging from **41,971.94 EGP** for **Home Improvement** loans to **43,289.41 EGP** for **Auto Loans**. The small differences indicate that annual income varies only slightly across loan types.

In [196]:
fig = px.bar(loan_type_income_stats.reset_index(),
            x="loan_type",
            y="mean",
            labels={"loan_type": "Loan Type", "mean": "Average Annual Income (EGP)"},
            title="Average Annual Income Across Loan Types")

fig.update_traces(texttemplate="%{y:.2f}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q19. How does loan origination volume change over time?

In [205]:
loan_origination_stats = (df.groupby(df["origination_date"].dt.to_period("M")).size().reset_index(name="loan_count"))

loan_origination_stats["origination_date"] = (loan_origination_stats["origination_date"].dt.to_timestamp())

loan_origination_stats

   origination_date  loan_count
0        2019-01-01         150
1        2019-02-01         135
2        2019-03-01         128
3        2019-04-01         145
4        2019-05-01         140
..              ...         ...
79       2025-08-01         135
80       2025-09-01         136
81       2025-10-01         166
82       2025-11-01         126
83       2025-12-01         149

[84 rows x 2 columns]

In [198]:
loan_origination_stats.loc[loan_origination_stats["loan_count"].idxmax()], loan_origination_stats.loc[loan_origination_stats["loan_count"].idxmin()]

(origination_date    2025-10-01 00:00:00
 loan_count                          166
 Name: 81, dtype: object,
 origination_date    2020-09-01 00:00:00
 loan_count                          111
 Name: 20, dtype: object)

**Answer:** Monthly loan origination volume ranges from **111 loans** in **September 2020** to **166 loans** in **October 2025**. The monthly number of originated loans varies over the period from **January 2019 to December 2025**, with no single consistent monthly level throughout the dataset.

In [199]:
fig = px.line(loan_origination_stats,
            x="origination_date",
            y="loan_count",
            labels={"origination_date": "Origination Date", "loan_count": "Number of Loans"},
            title="Monthly Loan Origination Volume Over Time")

fig.update_traces(mode="lines+markers")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q20. How does total loan amount change over time?

In [204]:
loan_amount_time_stats = (df.groupby(df["origination_date"].dt.to_period("M"))["loan_amount_egp"].sum().reset_index(name="total_loan_amount"))

loan_amount_time_stats["origination_date"] = (loan_amount_time_stats["origination_date"].dt.to_timestamp())

loan_amount_time_stats

   origination_date  total_loan_amount
0        2019-01-01           63873781
1        2019-02-01           55903138
2        2019-03-01           53689478
3        2019-04-01           60933675
4        2019-05-01           49607449
..              ...                ...
79       2025-08-01           56490979
80       2025-09-01           55988101
81       2025-10-01           62545375
82       2025-11-01           48899352
83       2025-12-01           54182436

[84 rows x 2 columns]

In [201]:
loan_amount_time_stats.loc[loan_amount_time_stats["total_loan_amount"].idxmax()], loan_amount_time_stats.loc[loan_amount_time_stats["total_loan_amount"].idxmin()]

(origination_date     2023-03-01 00:00:00
 total_loan_amount               68355359
 Name: 50, dtype: object,
 origination_date     2020-01-01 00:00:00
 total_loan_amount               33872278
 Name: 12, dtype: object)

**Answer:** The total monthly loan amount ranges from **33,872,278 EGP** in **January 2020** to **68,355,359 EGP** in **March 2023**. The total loan amount varies considerably across the period from **January 2019 to December 2025**, showing fluctuations in the value of loans originated each month.

In [203]:
fig = px.line(loan_amount_time_stats,
            x="origination_date",
            y="total_loan_amount",
            labels={"origination_date": "Origination Date", "total_loan_amount": "Total Loan Amount (EGP)"},
            title="Total Loan Amount Over Time")

fig.update_traces(mode="lines+markers", line_shape="spline")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

### Q21. How are loans distributed by their expected end year?

In [207]:
df["expected_end_date"] = df.apply(lambda row: row["origination_date"] + pd.DateOffset(months=int(row["term_months"])), axis=1)

df["expected_end_year"] = df["expected_end_date"].dt.year

expected_end_year_stats = (df["expected_end_year"].value_counts().sort_index())

expected_end_year_stats

expected_end_year
2020     109
2021     266
2022     456
2023     627
2024     919
2025    1129
2026    1340
2027    1215
2028    1023
2029     919
2030     866
2031     495
2032     323
2033     185
2034     267
2035     291
2036     111
2037     134
2038     144
2039     241
2040     250
2041     126
2042     116
2043     128
2044     147
2045     138
Name: count, dtype: int64

In [208]:
expected_end_year_stats.loc[expected_end_year_stats.idxmax()], expected_end_year_stats.loc[expected_end_year_stats.idxmin()]

(np.int64(1340), np.int64(109))

**Answer:** The expected loan end years range from **2020 to 2045**. The highest number of loans, **1,340 loans**, is expected to end in **2026**, while the lowest number, **109 loans**, is expected to end in **2020**. The distribution generally increases toward the mid-2020s, reaches its highest level in 2026, and then shows a gradual decline with some fluctuations through 2045.

In [209]:
fig = px.bar(expected_end_year_stats.reset_index(),
            x="expected_end_year",
            y="count",
            labels={"expected_end_year": "Expected End Year", "count": "Number of Loans"},
            title="Distribution of Loans by Expected End Year")

fig.update_traces(texttemplate="%{y}", textposition="outside")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()

In [213]:
fig = px.line(expected_end_year_stats.reset_index(),
            x="expected_end_year",
            y="count",
            labels={"expected_end_year": "Expected End Year", "count": "Number of Loans"},
            title="Expected Loan End Year Trend")

fig.update_traces(mode="lines+markers")

fig.update_layout(height=700, margin=dict(l=80, r=100, t=80, b=80))

fig.show()